[https]
host = "localhost"
port = 8080
paths = ["getOc2Cmd", "postOc2Cmd"]
log_level = "debug"

[mqtt]
client_id = "OC2-Twisted-368207455685"
host = "mosquito.olympus.mtn"
port = 1883
log_level = "debug"

[websockets]
host = "127.0.0.1"
port = 9000
log_level = "debug"

[devices]

[devices]
name = "Yuuki1"
profiles = ["sbom", "slpf"]
platform = "mac"
connection = "mqtt"
host = '127.0.0.1'
port = 1883
client_id = ''
username = ""
password = ""

[devices]
name = "Yuuki2"
profiles = ["database", "slpf"]
platform = "mac"
connection = "mqtt"
host = '127.0.0.1'
port = 1883
client_id = ''
username = ""
password = ""